### ISSUE TITLE
Consider adding vlucas/phpdotenv for LAMP stack users

### ISSUE THREAD

**Issue by vever001** [openeuropa/drupal-site-template#33]
Hello,

If I'm not mistaken, the .env file is only being read if we use docker.
LAMP stack users need to tweak the settings.php file manually and can't use the .env file.

I suggest to:
- add vlucas/phpdotenv (similar to drupal-project that uses it),
- add the .env file to .gitignore,
- and rename the current .env to .env.example

Related issue: https://github.com/openeuropa/drupal-site-template/issues/31

**Comment by brummbar** [comment]
Hello @vever001 , we will always only support installations through Docker.
