### ISSUE TITLE
PHP 7.2 required for doctrine/lexer 1.2.0

### ISSUE THREAD

**Issue by donquixote** [openeuropa/drupal-site-template#58]
_(version debfcbd1284644faa5fecf2cfcb9ec5af14e7126)_

When I try to run

    docker-compose exec web composer install

I get this

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (7.1.28) does not satisfy that requirement.
    - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (7.1.28) does not satisfy that requirement.
    - Installation request for doctrine/lexer 1.2.0 -> satisfiable by doctrine/lexer[1.2.0].
```

Changing PHP version to 7.2 fixes this.

**Comment by brummbar** [comment]
You used your local `composer` to create the project. Since you have PHP 7.2 locally, the dependencies have been calculated for that PHP version.
In this case, it's just a matter to run `docker-compose exec web composer update` to fix the composer lock file with the correct dependencies.
Closing as documentation already says to use docker also for the image creation.

**Comment by donquixote** [comment]
Thanks! Almost correct.
I used the new command that avoids using local php.
The command contains a parameter that specifies the php version as 7.1.
Unfortunately this did not work for me and I had to change the parameter to
7.2 to make it work.
I will try this again and see.

**Comment by brummbar** [comment]
We'll report to the image maintainers that 7.1 has issues on Linux machines.
Thanks for the reply, we can confirm that the PHP version is taken into account for package selection thus the error comes from the change of PHP version between project creation and usage.

**Comment by donquixote** [comment]
> I will try this again and see.

I think we should simply use 7.2 instead for this project (EUROFOUND).

**Comment by brummbar** [comment]
Which PHP version is used in projects hosted in the Commission machines is a decision to be taken with the devops of DIGIT.
