### ISSUE TITLE
Make this GitHub repository a Template

### ISSUE THREAD

**Issue by vemonet** [openeuropa/drupal-site-template#64]
GitHub allows to make your code repository a "Template"

This means there is a button "Use this template", alongside the "clone" button, which allows the user to use this repository as template to create another repository. It is basically like a fork, but you start with a clean commit history and can rename your project as you want

You can activate in the GitHub repository settings, just under the repository name

Example of a GitHub "Template" repository: https://github.com/MaastrichtU-IDS/d2s-transform-template

Also, I have a question unrelated to the issue: what does <dg-name> mean in the README? To create the project name properly, it is not explained anywhere

**Comment by brummbar** [comment]
Hello @vemonet , as written in the README this repo is not meant to be cloned nor used as template.

> Please note: this repository contains code that is necessary to generate a new Drupal 8 project, please read carefully this README.md. Do not clone this repository.

It is only meant to be used with the `composer create-project` command ([documentation](https://getcomposer.org/doc/03-cli.md#create-project)).

For the project name, most likely it would be assigned by the QA team. If you are using this project outside of Commission-hosted projects, then you can pick your favourite name.

At the end this is similar to the [Drupal composer template project](https://github.com/drupal-composer/drupal-project).
